HEX

3F200034 CONSTANT GPLEV0
3F200008 CONSTANT GPSEL2

\ GPIO 17
11 CONSTANT BUTTON_OFF
\ GPIO 16
10 CONSTANT BUTTON_RESET
\ GPIO 22
16 CONSTANT BUTTON_RIGHT
\ GPIO 23
17 CONSTANT BUTTON_DOWN
\ GPIO 24
18 CONSTANT BUTTON_UP
\ GPIO 27
1B CONSTANT BUTTON_LEFT
\ GPIO 25
19 CONSTANT BUTTON_ON

VARIABLE START_POINT
VARIABLE START_CHECK
VARIABLE STOP_CHECK

\ dato il numero della porta GPIO restiuiamo la maschera corretta
\ ( button_gpio -- gpio_mask)
: GPIO_MASK 1 SWAP LSHIFT ;

\ ( microseconds -- )
: DELAY BEGIN 1 - DUP 0 = UNTIL DROP ;

\ (color -- )
: VERIFY_R START_POINT @ 4 + DUP WHITE SWAP @ <> IF DUP START_POINT ! ! WIN ELSE 2DROP RESET FAIL THEN ;
: VERIFY_L START_POINT @ 4 - DUP WHITE SWAP @ <> IF DUP START_POINT ! ! WIN ELSE 2DROP RESET FAIL THEN ;
: VERIFY_U START_POINT @ 4 WIDTH * - DUP WHITE SWAP @ <> IF DUP START_POINT ! ! WIN ELSE 2DROP RESET FAIL THEN ;
: VERIFY_D START_POINT @ 4 WIDTH * + DUP WHITE SWAP @ <> IF DUP START_POINT ! ! WIN ELSE 2DROP RESET FAIL THEN ;

\ ( color button_GPIO -- ) : quando il bottone è premuto scrive il pixel a cui punta il frame buffer e lo incrementa
: WRITE_RIGHT BUTTON_RIGHT SWAP BEGIN 2DUP VERIFY_R 1000 DELAY GPIO_MASK GPLEV0 @ AND 0 = UNTIL 2DROP ;

: WRITE_LEFT BUTTON_LEFT SWAP BEGIN 2DUP VERIFY_L 1000 DELAY GPIO_MASK GPLEV0 @ AND 0 = UNTIL 2DROP ;
: WRITE_DOWN BUTTON_DOWN SWAP BEGIN 2DUP VERIFY_D 1000 DELAY GPIO_MASK GPLEV0 @ AND 0 = UNTIL 2DROP ;
: WRITE_UP BUTTON_UP SWAP BEGIN 2DUP VERIFY_U 1000 DELAY GPIO_MASK GPLEV0 @ AND 0 = UNTIL 2DROP ;

: ITER DUP 2DUP WRITE_RIGHT WRITE_LEFT WRITE_UP WRITE_DOWN ;

: BEGIN_CHECK 2EC 12C FIND_ADDRESS START_CHECK ! 2EC 14B FIND_ADDRESS STOP_CHECK ! ;

: AUX DUP START_POINT @ = IF STOP_CHECK @ START_CHECK ! DROP OK ELSE START_CHECK ! THEN ;

: WIN  BEGIN_CHECK BEGIN START_CHECK @ 4 WIDTH * + AUX START_CHECK @ STOP_CHECK @ = UNTIL  ;


: STOP 100 135 FIND_ADDRESS START_POINT ! RESET WRITE_START BEGIN GREEN ITER WIN BUTTON_OFF GPIO_MASK GPLEV0 @ AND 0 <> UNTIL DESKTOP MAZE ;

: START BUTTON_ON GPIO_MASK BEGIN DUP GPLEV0 @ AND 0 <> UNTIL DROP STOP ;


: SET_UP DESKTOP MAZE START ;


SET_UP





